### 1. Create Account (Initial Deposit: $25,000.00)
POST http://localhost:8080/api/accounts
Content-Type: application/json

{
  "name": "Main Trading Account",
  "initialCash": 25000.00
}

### 2. First Buy AAPL (10 shares * $150.00 = $1,500.00)
POST http://localhost:8080/api/accounts/1/buy
Content-Type: application/json

{
  "symbol": "AAPL",
  "quantity": 10,
  "price": 150.00
}

### 3. Second Buy AAPL (10 shares * $150.00 = $1,500.00)
POST http://localhost:8080/api/accounts/1/buy
Content-Type: application/json

{
  "symbol": "AAPL",
  "quantity": 10,
  "price": 150.00
}

### 4. Buy TSLA (10 shares * $200.00 = $2,000.00)
POST http://localhost:8080/api/accounts/1/buy
Content-Type: application/json

{
  "symbol": "TSLA",
  "quantity": 10,
  "price": 200.00
}


### 5. Get Account Positions (Verify AAPL: 20, TSLA: 10)
GET http://localhost:8080/api/accounts/1/positions



### 6. Set Market Price - AAPL ($230.00)
POST http://localhost:8080/api/market/prices
Content-Type: application/json

{
  "symbol": "AAPL",
  "price": 230.00
}



### 7. Set Market Price - TSLA ($340.00)
POST http://localhost:8080/api/market/prices
Content-Type: application/json

{
  "symbol": "TSLA",
  "price": 340.00
}

### 5. Get Account Positions (Verify AAPL: 20, TSLA: 10)
GET http://localhost:8080/api/accounts/1/balance

### 8.Test sell
POST http://localhost:8080/api/accounts/1/sell
Content-Type: application/json

{
  "symbol": "AAPL",
  "quantity": 5,
  "price": 230
}


### 5. Get Account Positions (Verify AAPL: 20, TSLA: 10)
GET http://localhost:8080/api/accounts/1/positions